import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  SafeAreaView,
  StatusBar,
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import {
  collection,
  doc,
  onSnapshot,
  query,
  orderBy,
  limit,
  setDoc,
  serverTimestamp,
  Timestamp,
} from 'firebase/firestore';

import { auth, db } from './firebase/config';
import { useTheme } from '../context/ThemeContext';
import PageHeader from '../components/PageHeader';
import useResponsiveLayout from '../hooks/useResponsiveLayout';
import { getWeekBoundaries } from '../utils/progressMetrics';
import {
  getWeeklyCompletion,
  isGoalDoneToday,
  subscribeDailyGoals,
  subscribeGoalCheckins,
  toggleGoalToday,
  DAILY_GOAL_WEEK_SUCCESS_THRESHOLD,
} from '../services/dailyGoals';

const formatDate = (date) => {
  try {
    return date.toLocaleDateString();
  } catch (error) {
    return '';
  }
};

/**
 * Pantalla de progreso general.
 * Combina información de metas, estados de ánimo, hábitos y reportes
 * semanales para mostrar la evolución del usuario a lo largo del tiempo.
 */
const ProgressScreen = ({ navigation }) => {
  const user = auth.currentUser;
  const userUid = user?.uid ?? null;
  const { colors } = useTheme();
  const {
    horizontalPadding,
    verticalPadding,
    maxContentWidth,
    safeTop,
    safeBottom,
  } = useResponsiveLayout({ maxContentWidth: 960, horizontalFactor: 0.06 });

  const contentWidthStyle = useMemo(
    () => ({
      width: '100%',
      maxWidth: maxContentWidth,
      alignSelf: 'center',
    }),
    [maxContentWidth],
  );

  const [statusMessage, setStatusMessage] = useState('');
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Metas diarias
  const [dailyGoals, setDailyGoals] = useState([]);
  const [dailyGoalsLoading, setDailyGoalsLoading] = useState(true);
  const [dailyCheckinsByGoal, setDailyCheckinsByGoal] = useState({});
  const [togglingDailyGoalId, setTogglingDailyGoalId] = useState(null);
  const dailyCheckinSubscriptionsRef = useRef({});

  // Reportes semanales basados en metas diarias
  const [weeklyReports, setWeeklyReports] = useState([]);
  const [reportsLoading, setReportsLoading] = useState(true);
  const [generatingReport, setGeneratingReport] = useState(false);

  const weekBoundaries = useMemo(() => getWeekBoundaries(new Date()), []);
  const weekLabel = useMemo(() => {
    const start = formatDate(weekBoundaries.weekStartDate);
    const end = formatDate(weekBoundaries.weekEndDate);
    return `${start} - ${end}`;
  }, [weekBoundaries]);
  const currentWeekKey = weekBoundaries.weekKey;

  const latestReport = useMemo(
    () => (weeklyReports.length ? weeklyReports[0] : null),
    [weeklyReports],
  );

  const latestOverview = useMemo(() => {
    if (!latestReport) {
      return {
        totalGoals: 0,
        goalsMet: 0,
        averageCompletionPercent: 0,
      };
    }
    const goals = Array.isArray(latestReport.goals) ? latestReport.goals : [];
    const totalGoals =
      typeof latestReport.overview?.totalGoals === 'number'
        ? latestReport.overview.totalGoals
        : goals.length;
    const goalsMet =
      typeof latestReport.overview?.goalsMet === 'number'
        ? latestReport.overview.goalsMet
        : goals.filter((g) => g.met).length;
    const overviewPercent =
      typeof latestReport.overview?.averageCompletionPercent === 'number'
        ? latestReport.overview.averageCompletionPercent
        : null;

    let averageCompletionPercent = 0;
    if (overviewPercent !== null) {
      averageCompletionPercent = overviewPercent;
    } else if (totalGoals) {
      const sum = goals.reduce(
        (acc, goal) => acc + Number(goal.completionPercent ?? 0),
        0,
      );
      averageCompletionPercent = sum / totalGoals;
    }

    return {
      totalGoals,
      goalsMet,
      averageCompletionPercent: Math.round(averageCompletionPercent || 0),
    };
  }, [latestReport]);

  // Limpia suscripciones de check-ins de metas diarias al desmontar
  useEffect(
    () => () => {
      const current = dailyCheckinSubscriptionsRef.current || {};
      Object.values(current).forEach((unsubscribe) => {
        if (typeof unsubscribe === 'function') {
          unsubscribe();
        }
      });
      dailyCheckinSubscriptionsRef.current = {};
    },
    [],
  );

  // Suscripción a metas diarias
  useEffect(() => {
    if (!userUid) {
      setDailyGoals([]);
      setDailyGoalsLoading(false);
      const current = dailyCheckinSubscriptionsRef.current || {};
      Object.values(current).forEach((unsubscribe) => {
        if (typeof unsubscribe === 'function') {
          unsubscribe();
        }
      });
      dailyCheckinSubscriptionsRef.current = {};
      setDailyCheckinsByGoal({});
      return undefined;
    }

    setDailyGoalsLoading(true);
    const unsubscribe = subscribeDailyGoals(userUid, (nextGoals) => {
      const activeDailyGoals = nextGoals.filter((goal) => goal.isActive !== false);
      setDailyGoals(activeDailyGoals);
      setDailyGoalsLoading(false);
    });

    return unsubscribe;
  }, [userUid]);

  // Suscripción a check-ins de cada meta diaria
  useEffect(() => {
    if (!userUid) {
      return;
    }

    const activeDailyIds = dailyGoals.map((goal) => goal.id);
    const current = dailyCheckinSubscriptionsRef.current || {};

    Object.keys(current).forEach((goalId) => {
      if (!activeDailyIds.includes(goalId)) {
        if (typeof current[goalId] === 'function') {
          current[goalId]();
        }
        delete current[goalId];
        setDailyCheckinsByGoal((prev) => {
          const next = { ...prev };
          delete next[goalId];
          return next;
        });
      }
    });

    activeDailyIds.forEach((goalId) => {
      if (!current[goalId]) {
        const unsubscribe = subscribeGoalCheckins(
          userUid,
          goalId,
          { maxDays: 140 },
          (checkins) => {
            setDailyCheckinsByGoal((prev) => ({
              ...prev,
              [goalId]: checkins,
            }));
          },
        );
        current[goalId] = unsubscribe;
      }
    });

    dailyCheckinSubscriptionsRef.current = current;
  }, [userUid, dailyGoals]);

  // Suscripción a reportes semanales de metas diarias
  useEffect(() => {
    if (!userUid) {
      setWeeklyReports([]);
      setReportsLoading(false);
      return undefined;
    }

    setReportsLoading(true);
    const reportsRef = collection(db, 'users', userUid, 'dailyGoalWeeklyReports');
    const reportsQuery = query(reportsRef, orderBy('weekStart', 'desc'), limit(12));

    const unsubscribe = onSnapshot(
      reportsQuery,
      (snapshot) => {
        const mapped = snapshot.docs.map((docSnapshot) => {
          const data = docSnapshot.data() ?? {};
          const weekStartDate =
            data.weekStart?.toDate && typeof data.weekStart.toDate === 'function'
              ? data.weekStart.toDate()
              : null;
          const weekEndDate =
            data.weekEnd?.toDate && typeof data.weekEnd.toDate === 'function'
              ? data.weekEnd.toDate()
              : null;
          const generatedAtDate =
            data.generatedAt?.toDate && typeof data.generatedAt.toDate === 'function'
              ? data.generatedAt.toDate()
              : null;
          const goals = Array.isArray(data.goals) ? data.goals : [];
          const overview = data.overview ?? {};

          return {
            id: docSnapshot.id,
            weekKey: data.weekKey ?? docSnapshot.id,
            goals,
            overview,
            weekStartDate,
            weekEndDate,
            generatedAtDate,
          };
        });
        setWeeklyReports(mapped);
        setReportsLoading(false);
      },
      () => {
        setWeeklyReports([]);
        setReportsLoading(false);
      },
    );

    return unsubscribe;
  }, [userUid]);

  const handleToggleDailyGoalToday = async (goal, doneToday) => {
    if (!userUid) {
      Alert.alert(
        'Sesión requerida',
        'Inicia sesión para registrar el estado de tus metas diarias.',
      );
      return;
    }

    if (doneToday) {
      Alert.alert(
        'Ya registrado',
        'Esta meta ya está marcada como realizada hoy.',
      );
      return;
    }

    setTogglingDailyGoalId(goal.id);
    try {
      await toggleGoalToday({ userUid, goalId: goal.id });
    } catch (error) {
      Alert.alert(
        'Error',
        'No se pudo guardar tu progreso, inténtalo de nuevo.',
      );
    } finally {
      setTogglingDailyGoalId(null);
    }
  };

  const handleGenerateReport = async () => {
    if (!userUid) {
      Alert.alert(
        'Sesión requerida',
        'Inicia sesión para generar tu reporte semanal.',
      );
      return;
    }

    if (!dailyGoals.length) {
      Alert.alert(
        'Metas diarias requeridas',
        'Crea al menos una meta diaria activa antes de generar un reporte.',
      );
      return;
    }

    if (generatingReport) {
      return;
    }

    setGeneratingReport(true);
    setStatusMessage('');

    try {
      const { weekStartDate, weekEndDate, weekKey } = getWeekBoundaries(new Date());

      const alreadyExists = weeklyReports.some(
        (report) => report.weekKey === weekKey,
      );
      if (alreadyExists) {
        setGeneratingReport(false);
        setStatusMessage('El reporte de esta semana ya estaba generado.');
        return;
      }

      const goalSummaries = dailyGoals.map((goal) => {
        const checkins = dailyCheckinsByGoal[goal.id] ?? [];
        const completion = getWeeklyCompletion(checkins, weekStartDate);
        const completionPercent = completion.completionPercent ?? 0;
        const met =
          completionPercent >=
          Math.round(DAILY_GOAL_WEEK_SUCCESS_THRESHOLD * 100);

        return {
          goalId: goal.id,
          title: goal.title,
          category: goal.category ?? 'custom',
          completedDays: completion.completedDays,
          totalDays: completion.totalDays,
          completionPercent,
          met,
        };
      });

      const totalGoals = goalSummaries.length;
      const goalsMet = goalSummaries.filter((g) => g.met).length;
      const averageCompletionPercent = totalGoals
        ? Math.round(
            goalSummaries.reduce(
              (acc, g) => acc + Number(g.completionPercent ?? 0),
              0,
            ) / totalGoals,
          )
        : 0;

      const reportsRef = collection(db, 'users', userUid, 'dailyGoalWeeklyReports');
      const reportRef = doc(reportsRef, weekKey);

      await setDoc(reportRef, {
        weekKey,
        weekStart: Timestamp.fromDate(weekStartDate),
        weekEnd: Timestamp.fromDate(weekEndDate),
        generatedAt: serverTimestamp(),
        goals: goalSummaries,
        overview: {
          totalGoals,
          goalsMet,
          averageCompletionPercent,
          successThresholdPercent: Math.round(
            DAILY_GOAL_WEEK_SUCCESS_THRESHOLD * 100,
          ),
        },
      });

      setGeneratingReport(false);
      setStatusMessage('Reporte semanal generado correctamente.');
    } catch (error) {
      setGeneratingReport(false);
      setStatusMessage('No pudimos generar el reporte.');
    }
  };

  // Autogeneración opcional basada en metas diarias
  useEffect(() => {
    if (autoGenerated) return;
    if (!userUid) return;
    if (generatingReport || reportsLoading) return;
    if (!dailyGoals.length) return;

    const hasCurrent = weeklyReports.some(
      (report) => report.weekKey === currentWeekKey,
    );
    if (hasCurrent) {
      setAutoGenerated(true);
      return;
    }

    handleGenerateReport();
    setAutoGenerated(true);
  }, [
    autoGenerated,
    userUid,
    generatingReport,
    reportsLoading,
    dailyGoals,
    weeklyReports,
    currentWeekKey,
  ]);

  return (
    <SafeAreaView
      style={[
        styles.container,
        {
          backgroundColor: colors.background,
          paddingTop: safeTop,
          paddingBottom: safeBottom,
        },
      ]}
    >
      <StatusBar
        barStyle={colors.statusBarStyle}
        backgroundColor={colors.background}
      />
      <ScrollView
        contentContainerStyle={[
          styles.scrollContainer,
          {
            paddingHorizontal: horizontalPadding,
            paddingTop: Math.max(verticalPadding * 0.5, 8),
            paddingBottom: Math.max(verticalPadding, 16),
          },
        ]}
        showsVerticalScrollIndicator={false}
        contentInsetAdjustmentBehavior="always"
      >
        <View style={[styles.content, contentWidthStyle]}>
          <PageHeader
            title="Metas y progreso"
            subtitle={`Semana del ${weekLabel}`}
          />

          {/* RESUMEN SEMANAL (basado en metas diarias) */}
          <View
            style={[
              styles.summaryCard,
              {
                backgroundColor: colors.surface,
                borderColor: colors.muted,
              },
            ]}
          >
            <View style={styles.summaryHeader}>
              <View style={styles.summaryTitleRow}>
                <Ionicons
                  name="analytics-outline"
                  size={20}
                  color={colors.primary}
                />
                <Text
                  style={[
                    styles.summaryTitle,
                    { color: colors.text },
                  ]}
                >
                  Resumen de la semana
                </Text>
              </View>
              <TouchableOpacity
                style={[
                  styles.generateButton,
                  { backgroundColor: colors.primary },
                  generatingReport && styles.generateButtonDisabled,
                ]}
                onPress={handleGenerateReport}
                disabled={generatingReport}
                activeOpacity={0.85}
              >
                {generatingReport ? (
                  <ActivityIndicator
                    size="small"
                    color={colors.primaryContrast}
                  />
                ) : (
                  <Ionicons
                    name="refresh"
                    size={16}
                    color={colors.primaryContrast}
                  />
                )}
                <Text
                  style={[
                    styles.generateLabel,
                    { color: colors.primaryContrast },
                  ]}
                >
                  Generar reporte
                </Text>
              </TouchableOpacity>
            </View>

            {latestReport ? (
              <>
                <View style={styles.summaryChips}>
                  <View
                    style={[
                      styles.summaryChip,
                      { backgroundColor: colors.primary + '1a' },
                    ]}
                  >
                    <Ionicons
                      name="checkmark-circle"
                      size={16}
                      color={colors.primary}
                    />
                    <Text
                      style={[
                        styles.summaryChipText,
                        { color: colors.primary },
                      ]}
                    >
                      {latestOverview.goalsMet} de {latestOverview.totalGoals}{' '}
                      metas diarias con buen cumplimiento
                    </Text>
                  </View>

                  <View
                    style={[
                      styles.summaryChip,
                      { backgroundColor: colors.muted },
                    ]}
                  >
                    <Ionicons
                      name="trending-up-outline"
                      size={16}
                      color={colors.text}
                    />
                    <Text
                      style={[
                        styles.summaryChipText,
                        { color: colors.text },
                      ]}
                    >
                      Promedio de cumplimiento semanal:{' '}
                      {latestOverview.averageCompletionPercent}%
                    </Text>
                  </View>
                </View>

                <View style={styles.goalDigest}>
                  {(latestReport.goals ?? []).map((goal) => {
                    const completedDays = Number(goal.completedDays ?? 0);
                    const totalDays = Number(goal.totalDays ?? 7);
                    const completionPercent = Math.round(
                      Number(goal.completionPercent ?? 0),
                    );

                    return (
                      <View
                        key={goal.goalId}
                        style={styles.goalDigestRow}
                      >
                        <Ionicons
                          name={
                            goal.met
                              ? 'checkmark-circle-outline'
                              : 'ellipse-outline'
                          }
                          size={16}
                          color={
                            goal.met
                              ? colors.primary
                              : colors.subText
                          }
                        />
                        <Text
                          style={[
                            styles.goalDigestText,
                            { color: colors.text },
                          ]}
                        >
                          {goal.title}: {completedDays} / {totalDays} días (
                          {completionPercent}
                          %)
                        </Text>
                      </View>
                    );
                  })}
                </View>
              </>
            ) : (
              <Text
                style={[
                  styles.summaryEmpty,
                  { color: colors.subText },
                ]}
              >
                Aún no hay un reporte generado para esta semana.
              </Text>
            )}
          </View>

          {statusMessage ? (
            <View
              style={[
                styles.statusBanner,
                { backgroundColor: colors.primary + '1a' },
              ]}
            >
              <Ionicons
                name="information-circle-outline"
                size={16}
                color={colors.primary}
              />
              <Text
                style={[
                  styles.statusText,
                  { color: colors.primary },
                ]}
              >
                {statusMessage}
              </Text>
            </View>
          ) : null}

          {/* METAS DIARIAS (CHECKLIST) */}
          <View style={styles.sectionHeader}>
            <Text
              style={[
                styles.sectionTitle,
                { color: colors.text },
              ]}
            >
              Metas diarias
            </Text>
            <TouchableOpacity
              style={[
                styles.newGoalButton,
                { borderColor: colors.primary },
              ]}
              onPress={() => navigation.navigate('DailyGoals')}
              activeOpacity={0.85}
            >
              <Ionicons
                name="checkmark-done-outline"
                size={18}
                color={colors.primary}
              />
              <Text
                style={[
                  styles.newGoalLabel,
                  { color: colors.primary },
                ]}
              >
                Gestionar
              </Text>
            </TouchableOpacity>
          </View>

          {dailyGoalsLoading ? (
            <View style={styles.loadingBlock}>
              <ActivityIndicator
                size="small"
                color={colors.primary}
              />
              <Text
                style={[
                  styles.loadingText,
                  { color: colors.subText },
                ]}
              >
                Cargando metas diarias...
              </Text>
            </View>
          ) : dailyGoals.length ? (
            dailyGoals.map((goal) => {
              const checkins = dailyCheckinsByGoal[goal.id] ?? [];
              const doneToday = isGoalDoneToday(goal.id, checkins);
              const weekly = getWeeklyCompletion(checkins, new Date());

              return (
                <View
                  key={goal.id}
                  style={[
                    styles.dailyGoalCard,
                    {
                      backgroundColor: colors.surface,
                      borderColor: colors.muted,
                    },
                  ]}
                >
                  <View style={styles.dailyGoalTopRow}>
                    <View style={styles.dailyGoalTitleBlock}>
                      <Text
                        style={[
                          styles.dailyGoalTitle,
                          { color: colors.text },
                        ]}
                      >
                        {goal.title}
                      </Text>
                      {goal.category ? (
                        <Text
                          style={[
                            styles.dailyGoalCategory,
                            { color: colors.subText },
                          ]}
                        >
                          Categoría: {goal.category}
                        </Text>
                      ) : null}
                    </View>
                    <TouchableOpacity
                      style={[
                        styles.dailyTodayToggle,
                        {
                          borderColor: doneToday
                            ? colors.primary
                            : colors.muted,
                          backgroundColor: doneToday
                            ? colors.primary + '22'
                            : colors.muted,
                        },
                      ]}
                      onPress={() =>
                        handleToggleDailyGoalToday(goal, doneToday)
                      }
                      disabled={togglingDailyGoalId === goal.id}
                      activeOpacity={0.85}
                    >
                      {togglingDailyGoalId === goal.id ? (
                        <ActivityIndicator
                          size="small"
                          color={
                            doneToday
                              ? colors.primary
                              : colors.text
                          }
                        />
                      ) : (
                        <Ionicons
                          name={
                            doneToday
                              ? 'checkmark-circle'
                              : 'ellipse-outline'
                          }
                          size={16}
                          color={
                            doneToday
                              ? colors.primary
                              : colors.text
                          }
                        />
                      )}
                      <Text
                        style={[
                          styles.dailyTodayToggleLabel,
                          {
                            color: doneToday
                              ? colors.primary
                              : colors.text,
                          },
                        ]}
                      >
                        {doneToday ? 'Hecho hoy' : 'No hecho'}
                      </Text>
                    </TouchableOpacity>
                  </View>

                  <View style={styles.dailyGoalMetaRow}>
                    <Text
                      style={[
                        styles.dailyGoalMetaText,
                        { color: colors.subText },
                      ]}
                    >
                      Cumplimiento semanal: {weekly.completedDays}/
                      {weekly.totalDays} ({weekly.completionPercent}%)
                    </Text>
                    <Text
                      style={[
                        styles.dailyGoalMetaText,
                        { color: colors.subText },
                      ]}
                    >
                      Racha: {goal.currentStreakWeeks ?? 0} / mejor{' '}
                      {goal.bestStreakWeeks ?? 0} semanas
                    </Text>
                  </View>
                </View>
              );
            })
          ) : (
            <View style={styles.emptyBlock}>
              <Ionicons
                name="checkmark-circle-outline"
                size={22}
                color={colors.subText}
              />
              <Text
                style={[
                  styles.emptyText,
                  { color: colors.subText },
                ]}
              >
                Aún no tienes metas diarias. Toca "Gestionar" para crear la primera.
              </Text>
            </View>
          )}

          {/* HISTORIAL DE REPORTES (metas diarias) */}
          <View style={styles.sectionHeader}>
            <Text
              style={[
                styles.sectionTitle,
                { color: colors.text },
              ]}
            >
              Historial de reportes
            </Text>
          </View>

          {reportsLoading ? (
            <View style={styles.loadingBlock}>
              <ActivityIndicator
                size="small"
                color={colors.primary}
              />
              <Text
                style={[
                  styles.loadingText,
                  { color: colors.subText },
                ]}
              >
                Cargando reportes...
              </Text>
            </View>
          ) : weeklyReports.length ? (
            weeklyReports.map((report) => {
              const goals = Array.isArray(report.goals) ? report.goals : [];
              const overview = report.overview ?? {};
              const totalGoals =
                typeof overview.totalGoals === 'number'
                  ? overview.totalGoals
                  : goals.length;
              const goalsMet =
                typeof overview.goalsMet === 'number'
                  ? overview.goalsMet
                  : goals.filter((g) => g.met).length;
              let averageCompletionPercent =
                typeof overview.averageCompletionPercent === 'number'
                  ? overview.averageCompletionPercent
                  : 0;

              if (!averageCompletionPercent && totalGoals) {
                const sum = goals.reduce(
                  (acc, g) => acc + Number(g.completionPercent ?? 0),
                  0,
                );
                averageCompletionPercent = sum / totalGoals;
              }

              const averagePercentRounded = Math.round(
                averageCompletionPercent || 0,
              );

              return (
                <TouchableOpacity
                  key={report.id ?? report.weekKey}
                  style={[
                    styles.reportCard,
                    {
                      backgroundColor: colors.surface,
                      borderColor: colors.muted,
                    },
                  ]}
                  onPress={() =>
                    navigation.navigate('ReportDetail', {
                      reportId: report.id ?? report.weekKey,
                      report,
                    })
                  }
                  activeOpacity={0.85}
                >
                  <View style={styles.reportHeader}>
                    <Text
                      style={[
                        styles.reportTitle,
                        { color: colors.text },
                      ]}
                    >
                      Semana {report.weekKey}
                    </Text>
                    <Text
                      style={[
                        styles.reportMoodPill,
                        {
                          color: colors.primary,
                          borderColor: colors.primary,
                        },
                      ]}
                    >
                      {averagePercentRounded}% promedio
                    </Text>
                  </View>

                  <Text
                    style={[
                      styles.reportLine,
                      { color: colors.subText },
                    ]}
                  >
                    Metas diarias con buen cumplimiento: {goalsMet} de{' '}
                    {totalGoals}
                  </Text>
                  <Text
                    style={[
                      styles.reportLine,
                      { color: colors.subText },
                    ]}
                  >
                    Promedio semanal de cumplimiento: {averagePercentRounded}%
                  </Text>
                  <Text
                    style={[
                      styles.reportSubtitle,
                      { color: colors.subText },
                    ]}
                  >
                    Generado{' '}
                    {formatDate(
                      report.generatedAtDate ?? new Date(),
                    )}
                  </Text>
                </TouchableOpacity>
              );
            })
          ) : (
            <View style={styles.emptyBlock}>
              <Ionicons
                name="document-text-outline"
                size={22}
                color={colors.subText}
              />
              <Text
                style={[
                  styles.emptyText,
                  { color: colors.subText },
                ]}
              >
                Cuando generes tus reportes semanales, aparecerán aquí.
              </Text>
            </View>
          )}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

export default ProgressScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
  },
  content: {
    width: '100%',
    gap: 20,
  },
  summaryCard: {
    borderWidth: 1,
    borderRadius: 24,
    padding: 20,
    gap: 16,
  },
  summaryHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
  },
  summaryTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  generateButtonDisabled: {
    opacity: 0.6,
  },
  generateLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  summaryChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  summaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  summaryChipText: {
    fontSize: 12,
    fontWeight: '600',
  },
  summaryEmpty: {
    fontSize: 13,
  },
  goalDigest: {
    gap: 6,
  },
  goalDigestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  goalDigestText: {
    fontSize: 13,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  newGoalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  newGoalLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  loadingBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
  },
  loadingText: {
    fontSize: 13,
  },
  emptyBlock: {
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(107,114,128,0.08)',
  },
  emptyText: {
    fontSize: 13,
    textAlign: 'center',
  },
  reportCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    gap: 6,
  },
  reportHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  reportTitle: {
    fontSize: 15,
    fontWeight: '600',
    flexShrink: 1,
    minWidth: 0,
  },
  reportMoodPill: {
    fontSize: 11,
    fontWeight: '600',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    alignSelf: 'flex-start',
    flexShrink: 1,
  },
  reportLine: {
    fontSize: 12,
  },
  reportSubtitle: {
    fontSize: 12,
  },
  dailyGoalCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    gap: 10,
  },
  dailyGoalTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dailyGoalTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  dailyGoalTitle: {
    fontSize: 15,
    fontWeight: '600',
  },
  dailyGoalCategory: {
    fontSize: 12,
  },
  dailyTodayToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dailyTodayToggleLabel: {
    fontSize: 12,
    fontWeight: '500',
  },
  dailyGoalMetaRow: {
    marginTop: 4,
    gap: 2,
  },
  dailyGoalMetaText: {
    fontSize: 12,
  },
});