import React, { useEffect, useMemo, useState } from 'react';
import {
  SafeAreaView,
  StatusBar,
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

import { useTheme } from '../context/ThemeContext';
import useResponsiveLayout from '../hooks/useResponsiveLayout';
import { useGoalProgress } from '../hooks/useGoalProgress';
import { GoalFormModal } from '../components/progress/GoalFormModal';
import { GoalActivityModal } from '../components/progress/GoalActivityModal';
import { GoalProgressCard } from '../components/progress/GoalProgressCard';
import { getWeekBoundaries } from '../utils/progressMetrics';

const formatDate = (date) => {
  try {
    return date.toLocaleDateString();
  } catch (error) {
    return '';
  }
};

/**
 * Convierte un valor numérico de valencia (-2 a 2)
 * en una frase simple para el usuario.
 */
const describeMoodFromValence = (value) => {
  if (value === null || value === undefined) return 'Sin registro de emociones';

  const num = Number(value);
  if (Number.isNaN(num)) return 'Sin registro de emociones';

  if (num < -0.5) return 'Día difícil';
  if (num <= 0.5) return 'Estable';
  return 'Buen día';
};

const ProgressScreen = ({ navigation }) => {
  const { colors } = useTheme();
  const {
    horizontalPadding,
    verticalPadding,
    maxContentWidth,
    safeTop,
    safeBottom,
  } = useResponsiveLayout({ maxContentWidth: 960, horizontalFactor: 0.06 });

  const contentWidthStyle = useMemo(
    () => ({
      width: '100%',
      maxWidth: maxContentWidth,
      alignSelf: 'center',
    }),
    [maxContentWidth],
  );

  const {
    activeGoals,
    goals,
    latestReport,
    weeklyReports,
    latestSnapshots,
    generateWeeklyReport,
    logGoalActivity,
    createGoal,
    updateGoal,
    archiveGoal,
    deleteGoal, // puede venir undefined; lo tratamos con fallback
    isLoading,
    generatingReport,
    currentWeekKey,
  } = useGoalProgress();

  const [goalModalVisible, setGoalModalVisible] = useState(false);
  const [activityModalGoal, setActivityModalGoal] = useState(null);
  const [editingGoal, setEditingGoal] = useState(null);
  const [statusMessage, setStatusMessage] = useState('');
  const [autoGenerated, setAutoGenerated] = useState(false);

  const weekBoundaries = useMemo(() => getWeekBoundaries(new Date()), []);
  const weekLabel = useMemo(() => {
    const start = formatDate(weekBoundaries.weekStartDate);
    const end = formatDate(weekBoundaries.weekEndDate);
    return `${start} - ${end}`;
  }, [weekBoundaries]);

  const handleOpenCreateModal = () => {
    setEditingGoal(null);
    setGoalModalVisible(true);
    setStatusMessage('');
  };

  const handleSubmitGoal = async (payload) => {
    try {
      if (editingGoal) {
        await updateGoal(editingGoal.id, payload);
      } else {
        await createGoal(payload);
      }
      setGoalModalVisible(false);
    } catch (error) {
      setStatusMessage(error.message ?? 'No se pudo guardar la meta.');
    }
  };

  const handleEditGoal = (goal) => {
    setEditingGoal(goal);
    setGoalModalVisible(true);
    setStatusMessage('');
  };

  const handleArchiveGoal = (goal) => {
    Alert.alert(
      'Archivar meta',
      'Si archivas esta meta, dejará de generar reportes. Puedes reactivarla cuando quieras.',
      [
        { text: 'Cancelar', style: 'cancel' },
        {
          text: 'Archivar',
          style: 'destructive',
          onPress: () =>
            archiveGoal(goal.id).catch(() => {
              Alert.alert('Error', 'No pudimos archivar la meta.');
            }),
        },
      ],
    );
  };

  const handleDeleteGoal = (goal) => {
    Alert.alert(
      'Eliminar meta',
      'Esta acción eliminará la meta de tu vista actual. ¿Seguro que quieres continuar?',
      [
        { text: 'Cancelar', style: 'cancel' },
        {
          text: 'Eliminar',
          style: 'destructive',
          onPress: async () => {
            try {
              if (typeof deleteGoal === 'function') {
                await deleteGoal(goal.id);
              } else {
                // Respaldo: si no existe deleteGoal, al menos la archivamos
                await archiveGoal(goal.id);
              }
            } catch (error) {
              Alert.alert('Error', 'No pudimos eliminar la meta.');
            }
          },
        },
      ],
    );
  };

  const handleGenerateReport = async () => {
    try {
      const result = await generateWeeklyReport({});
      if (result?.skipped) {
        setStatusMessage('El reporte de esta semana ya estaba generado.');
      } else {
        setStatusMessage('Reporte semanal generado correctamente.');
      }
    } catch (error) {
      setStatusMessage(error.message ?? 'No pudimos generar el reporte.');
    }
  };

  const handleLogActivity = (goal) => {
    setActivityModalGoal(goal);
  };

  const handleSubmitActivity = async ({ goalId, value, note }) => {
    try {
      await logGoalActivity({ goalId, value, note });
      setActivityModalGoal(null);
    } catch (error) {
      Alert.alert('Error', 'No pudimos registrar la actividad.');
    }
  };

  const themeColors = useMemo(
    () => ({
      surface: colors.surface,
      border: colors.muted,
      text: colors.text,
      subText: colors.subText,
      primary: colors.primary,
      primaryContrast: colors.primaryContrast,
      danger: colors.danger ?? '#ef4444',
      success: '#16a34a',
    }),
    [colors],
  );

  const orderedGoals = useMemo(() => {
    return [...activeGoals].sort((a, b) => {
      const snapA = latestSnapshots[a.id];
      const snapB = latestSnapshots[b.id];
      const progressA = snapA?.progressPercent ?? (snapA?.met ? 100 : 0);
      const progressB = snapB?.progressPercent ?? (snapB?.met ? 100 : 0);
      return progressB - progressA;
    });
  }, [activeGoals, latestSnapshots]);

  useEffect(() => {
    if (autoGenerated) return;
    if (isLoading || generatingReport) return;
    if (!activeGoals.length) return;

    const hasCurrentReport = weeklyReports.some(
      (report) => report.weekKey === currentWeekKey,
    );
    if (hasCurrentReport) {
      setAutoGenerated(true);
      return;
    }

    generateWeeklyReport({})
      .then((result) => {
        if (result?.skipped) {
          setStatusMessage('Ya cuentas con un reporte para esta semana.');
        } else {
          setStatusMessage('Generamos un reporte base con tus datos recientes.');
        }
      })
      .catch(() => {
        setStatusMessage('No pudimos generar el reporte automáticamente.');
      })
      .finally(() => setAutoGenerated(true));
  }, [
    autoGenerated,
    isLoading,
    generatingReport,
    activeGoals,
    weeklyReports,
    currentWeekKey,
    generateWeeklyReport,
  ]);

  // Valor de ánimo promedio de la semana actual (numérico)
  const latestValence = latestReport?.moodOverview?.averageValence ?? null;
  // Texto para el chip de ánimo
  const latestMoodLabel = (() => {
    const hasEntries =
      (latestReport?.moodOverview?.entriesCount ?? 0) > 0;
    if (!hasEntries) return 'Sin registro de emociones';
    return describeMoodFromValence(latestValence);
  })();

  return (
    <SafeAreaView
      style={[
        styles.container,
        {
          backgroundColor: colors.background,
          paddingTop: safeTop,
          paddingBottom: safeBottom,
        },
      ]}
    >
      <StatusBar
        barStyle={colors.statusBarStyle}
        backgroundColor={colors.background}
      />
      <ScrollView
        contentContainerStyle={[
          styles.scrollContainer,
          {
            paddingHorizontal: horizontalPadding,
            paddingTop: Math.max(verticalPadding * 0.5, 8),
            paddingBottom: Math.max(verticalPadding, 16),
          },
        ]}
        showsVerticalScrollIndicator={false}
        contentInsetAdjustmentBehavior="always"
      >
        <View style={[styles.content, contentWidthStyle]}>
          {/* HEADER */}
          <View style={styles.header}>
            <TouchableOpacity
              style={[styles.backButton, { borderColor: colors.muted }]}
              onPress={() => navigation.goBack()}
              activeOpacity={0.85}
            >
              <Ionicons
                name="chevron-back"
                size={22}
                color={colors.text}
              />
              <Text
                style={[styles.backLabel, { color: colors.text }]}
              >
                Volver
              </Text>
            </TouchableOpacity>
            <View style={styles.headerText}>
              <Text
                style={[styles.title, { color: colors.text }]}
              >
                Progreso semanal
              </Text>
              <Text
                style={[styles.subtitle, { color: colors.subText }]}
              >
                Semana del {weekLabel}
              </Text>
            </View>
          </View>

          {/* RESUMEN SEMANAL */}
          <View
            style={[
              styles.summaryCard,
              {
                backgroundColor: colors.surface,
                borderColor: colors.muted,
              },
            ]}
          >
            <View style={styles.summaryHeader}>
              <View style={styles.summaryTitleRow}>
                <Ionicons
                  name="analytics-outline"
                  size={20}
                  color={colors.primary}
                />
                <Text
                  style={[
                    styles.summaryTitle,
                    { color: colors.text },
                  ]}
                >
                  Resumen de la semana
                </Text>
              </View>
              <TouchableOpacity
                style={[
                  styles.generateButton,
                  { backgroundColor: colors.primary },
                  generatingReport && styles.generateButtonDisabled,
                ]}
                onPress={handleGenerateReport}
                disabled={generatingReport}
                activeOpacity={0.85}
              >
                {generatingReport ? (
                  <ActivityIndicator
                    size="small"
                    color={colors.primaryContrast}
                  />
                ) : (
                  <Ionicons
                    name="refresh"
                    size={16}
                    color={colors.primaryContrast}
                  />
                )}
                <Text
                  style={[
                    styles.generateLabel,
                    { color: colors.primaryContrast },
                  ]}
                >
                  Generar reporte
                </Text>
              </TouchableOpacity>
            </View>

            {latestReport ? (
              <>
                <View style={styles.summaryChips}>
                  <View
                    style={[
                      styles.summaryChip,
                      { backgroundColor: colors.primary + '1a' },
                    ]}
                  >
                    <Ionicons
                      name="checkmark-circle"
                      size={16}
                      color={colors.primary}
                    />
                    <Text
                      style={[
                        styles.summaryChipText,
                        { color: colors.primary },
                      ]}
                    >
                      {
                        latestReport.goals.filter(
                          (item) => item.met,
                        ).length
                      }{' '}
                      de {latestReport.goals.length} metas cumplidas
                    </Text>
                  </View>

                  <View
                    style={[
                      styles.summaryChip,
                      { backgroundColor: colors.muted },
                    ]}
                  >
                    <Ionicons
                      name="pulse-outline"
                      size={16}
                      color={colors.text}
                    />
                    <Text
                      style={[
                        styles.summaryChipText,
                        { color: colors.text },
                      ]}
                    >
                      Estado emocional: {latestMoodLabel}
                    </Text>
                  </View>

                  <View
                    style={[
                      styles.summaryChip,
                      { backgroundColor: colors.muted },
                    ]}
                  >
                    <Ionicons
                      name="leaf-outline"
                      size={16}
                      color={colors.text}
                    />
                    <Text
                      style={[
                        styles.summaryChipText,
                        { color: colors.text },
                      ]}
                    >
                      {latestReport.habitOverview?.count ?? 0}{' '}
                      registros de hábitos
                    </Text>
                  </View>
                </View>

                <View style={styles.goalDigest}>
                  {latestReport.goals.map((goal) => (
                    <View
                      key={goal.goalId}
                      style={styles.goalDigestRow}
                    >
                      <Ionicons
                        name={
                          goal.met
                            ? 'checkmark-circle-outline'
                            : 'ellipse-outline'
                        }
                        size={16}
                        color={
                          goal.met
                            ? colors.primary
                            : colors.subText
                        }
                      />
                      <Text
                        style={[
                          styles.goalDigestText,
                          { color: colors.text },
                        ]}
                      >
                        {goal.title}: {goal.actualValue} /{' '}
                        {goal.targetValue}{' '}
                        {goal.measurementLabel ?? ''}
                      </Text>
                    </View>
                  ))}
                </View>
              </>
            ) : (
              <Text
                style={[
                  styles.summaryEmpty,
                  { color: colors.subText },
                ]}
              >
                Aún no hay un reporte generado para esta semana.
              </Text>
            )}
          </View>

          {/* METAS ACTIVAS */}
          <View style={styles.sectionHeader}>
            <Text
              style={[
                styles.sectionTitle,
                { color: colors.text },
              ]}
            >
              Metas activas
            </Text>
            <TouchableOpacity
              style={[
                styles.newGoalButton,
                { borderColor: colors.primary },
              ]}
              onPress={handleOpenCreateModal}
              activeOpacity={0.85}
            >
              <Ionicons
                name="add"
                size={18}
                color={colors.primary}
              />
              <Text
                style={[
                  styles.newGoalLabel,
                  { color: colors.primary },
                ]}
              >
                Nueva meta
              </Text>
            </TouchableOpacity>
          </View>

          {statusMessage ? (
            <View
              style={[
                styles.statusBanner,
                { backgroundColor: colors.primary + '1a' },
              ]}
            >
              <Ionicons
                name="information-circle-outline"
                size={16}
                color={colors.primary}
              />
              <Text
                style={[
                  styles.statusText,
                  { color: colors.primary },
                ]}
              >
                {statusMessage}
              </Text>
            </View>
          ) : null}

          {isLoading ? (
            <View style={styles.loadingBlock}>
              <ActivityIndicator
                size="small"
                color={colors.primary}
              />
              <Text
                style={[
                  styles.loadingText,
                  { color: colors.subText },
                ]}
              >
                Cargando metas...
              </Text>
            </View>
          ) : orderedGoals.length ? (
            orderedGoals.map((goal) => (
              <GoalProgressCard
                key={goal.id}
                goal={goal}
                snapshot={latestSnapshots[goal.id]}
                onEdit={handleEditGoal}
                onArchive={handleArchiveGoal}
                onDelete={handleDeleteGoal} // NUEVO: botón eliminar dentro de la tarjeta
                onLogActivity={handleLogActivity}
                colors={themeColors}
              />
            ))
          ) : (
            <View style={styles.emptyBlock}>
              <Ionicons
                name="flag-outline"
                size={22}
                color={colors.subText}
              />
              <Text
                style={[
                  styles.emptyText,
                  { color: colors.subText },
                ]}
              >
                Aún no tienes metas activas. Crea la primera para
                empezar a medir tu progreso.
              </Text>
            </View>
          )}

          {/* HISTORIAL DE REPORTES */}
          <View style={styles.sectionHeader}>
            <Text
              style={[
                styles.sectionTitle,
                { color: colors.text },
              ]}
            >
              Historial de reportes
            </Text>
          </View>

          {weeklyReports.length ? (
            weeklyReports.map((report) => {
              const goalsMet = report.goals?.filter((g) => g.met).length ?? 0;
              const goalsTotal = report.goals?.length ?? 0;

              const val =
                report.moodOverview?.averageValence ?? null;
              const entriesCount =
                report.moodOverview?.entriesCount ?? 0;
              const hasMoodData = entriesCount > 0;
              const moodLabel = hasMoodData
                ? describeMoodFromValence(val)
                : 'Sin registro de emociones';

              const habitCount =
                report.habitOverview?.count ?? 0;

              const moodColor =
                moodLabel === 'Día difícil'
                  ? (colors.danger ?? '#ef4444')
                  : moodLabel === 'Buen día'
                  ? colors.primary
                  : colors.subText;

              return (
                <TouchableOpacity
                  key={report.id ?? report.weekKey}
                  style={[
                    styles.reportCard,
                    {
                      backgroundColor: colors.surface,
                      borderColor: colors.muted,
                    },
                  ]}
                  onPress={() =>
                    navigation.navigate('ReportDetail', {
                      reportId: report.id ?? report.weekKey,
                      report,
                    })
                  }
                  activeOpacity={0.85}
                >
                  <View style={styles.reportHeader}>
                    <Text
                      style={[
                        styles.reportTitle,
                        { color: colors.text },
                      ]}
                    >
                      Semana {report.weekKey}
                    </Text>
                    <Text
                      style={[
                        styles.reportMoodPill,
                        { color: moodColor, borderColor: moodColor },
                      ]}
                    >
                      {moodLabel}
                    </Text>
                  </View>

                  <Text
                    style={[
                      styles.reportLine,
                      { color: colors.subText },
                    ]}
                  >
                    Metas cumplidas: {goalsMet} de {goalsTotal}
                  </Text>
                  <Text
                    style={[
                      styles.reportLine,
                      { color: colors.subText },
                    ]}
                  >
                    Hábitos registrados: {habitCount}
                  </Text>
                  <Text
                    style={[
                      styles.reportSubtitle,
                      { color: colors.subText },
                    ]}
                  >
                    Generado{' '}
                    {formatDate(
                      report.generatedAtDate ?? new Date(),
                    )}
                  </Text>
                </TouchableOpacity>
              );
            })
          ) : (
            <View style={styles.emptyBlock}>
              <Ionicons
                name="document-text-outline"
                size={22}
                color={colors.subText}
              />
              <Text
                style={[
                  styles.emptyText,
                  { color: colors.subText },
                ]}
              >
                Cuando generes tus reportes semanales, aparecerán
                aquí.
              </Text>
            </View>
          )}
        </View>
      </ScrollView>

      {/* MODAL CREAR / EDITAR META */}
      <GoalFormModal
        visible={goalModalVisible}
        onClose={() => setGoalModalVisible(false)}
        onSubmit={handleSubmitGoal}
        initialGoal={editingGoal}
      />

      {/* MODAL REGISTRAR ACTIVIDAD */}
      <GoalActivityModal
        visible={Boolean(activityModalGoal)}
        onClose={() => setActivityModalGoal(null)}
        goal={activityModalGoal}
        onSubmit={handleSubmitActivity}
      />
    </SafeAreaView>
  );
};

export default ProgressScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
  },
  content: {
    width: '100%',
    gap: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  backLabel: {
    fontSize: 13,
    fontWeight: '500',
  },
  headerText: {
    flex: 1,
    gap: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
  },
  subtitle: {
    fontSize: 13,
  },
  summaryCard: {
    borderWidth: 1,
    borderRadius: 24,
    padding: 20,
    gap: 16,
  },
  summaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  generateButtonDisabled: {
    opacity: 0.6,
  },
  generateLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  summaryChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  summaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  summaryChipText: {
    fontSize: 12,
    fontWeight: '600',
  },
  summaryEmpty: {
    fontSize: 13,
  },
  goalDigest: {
    gap: 6,
  },
  goalDigestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  goalDigestText: {
    fontSize: 13,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  newGoalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  newGoalLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  loadingBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
  },
  loadingText: {
    fontSize: 13,
  },
  emptyBlock: {
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(107,114,128,0.08)',
  },
  emptyText: {
    fontSize: 13,
    textAlign: 'center',
  },
  reportCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    gap: 6,
  },
  reportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportTitle: {
    fontSize: 15,
    fontWeight: '600',
  },
  reportMoodPill: {
    fontSize: 11,
    fontWeight: '600',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
  },
  reportLine: {
    fontSize: 12,
  },
  reportSubtitle: {
    fontSize: 12,
  },
});
